app:
  port: 8080
  page_size: 5
  templates_pattern: "adapter/templates/*.html"
db:
  dsn: "test_user:test_pass@tcp(127.0.0.1:3306)/lr_event_book?charset=utf8mb4&parseTime=True&loc=Local"
mq:
  brokers:
    - localhost:9094
  topic: "lr-book-searches"
remote:
  trend_url: "http://localhost:8081/trends"
  rec_url: "http://localhost:8082/recommendations?uid="
