app:
  port: 8080
  page_size: 5
  templates_pattern: "templates/*.html"
db:
  dsn: "test_user:test_pass@tcp(mysql:3306)/lr_event_book?charset=utf8mb4&parseTime=True&loc=Local"
mq:
  brokers:
    - kafka:9092
  topic: "lr-book-searches"
remote:
  trend_url: "http://lr-event-books-trend:8081/trends"
  rec_url: "http://lr-event-books-rec:8082/recommendations?uid="
